create extension if not exists pgcrypto;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users (id) on delete cascade,
  added_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

drop policy if exists "admin_users_select_self" on public.admin_users;
create policy "admin_users_select_self"
on public.admin_users for select
using (auth.uid() = user_id);

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.admin_users au
    where au.user_id = auth.uid()
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

grant select, insert, delete on public.admin_users to authenticated;

grant select, insert, delete on public.admin_users to service_role;

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete set null,
  session_id text not null,
  event_name text not null,
  event_props jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_event_name_idx
  on public.analytics_events (event_name);

create index if not exists analytics_events_occurred_at_idx
  on public.analytics_events (occurred_at desc);

create index if not exists analytics_events_audio_id_idx
  on public.analytics_events ((event_props->>'audio_id'));

alter table public.analytics_events enable row level security;

grant insert on public.analytics_events to anon, authenticated;
grant select on public.analytics_events to authenticated;
grant usage, select on sequence public.analytics_events_id_seq to anon, authenticated;

drop policy if exists "analytics_events_insert_public" on public.analytics_events;
create policy "analytics_events_insert_public"
on public.analytics_events for insert
to anon, authenticated
with check (true);

drop policy if exists "analytics_events_admin_select" on public.analytics_events;
create policy "analytics_events_admin_select"
on public.analytics_events for select
to authenticated
using (public.is_admin());

create or replace function public.set_analytics_event_user_id()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is not null then
    new.user_id := auth.uid();
  end if;
  return new;
end;
$$;

drop trigger if exists analytics_events_set_user on public.analytics_events;
create trigger analytics_events_set_user
before insert on public.analytics_events
for each row
execute function public.set_analytics_event_user_id();

create or replace view public.analytics_audio_summary as
select
  event_props->>'audio_id' as audio_id,
  count(*) filter (where event_name = 'audio_play')::int as plays,
  count(*) filter (where event_name = 'audio_complete')::int as completes,
  count(*) filter (where event_name = 'audio_abandon')::int as abandons,
  case
    when count(*) filter (where event_name = 'audio_play') = 0 then 0::numeric
    else round(
      (count(*) filter (where event_name = 'audio_complete'))::numeric
      / nullif(count(*) filter (where event_name = 'audio_play'), 0),
      4
    )
  end as completion_rate
from public.analytics_events
where event_name in ('audio_play', 'audio_complete', 'audio_abandon')
  and coalesce(event_props->>'audio_id', '') <> ''
group by event_props->>'audio_id';
alter view public.analytics_audio_summary set (security_invoker = true);

create or replace view public.analytics_tailored_summary as
select
  count(*) filter (where event_name = 'tailored_session_start')::int as sessions_started,
  count(*) filter (where event_name = 'tailored_session_complete')::int as sessions_completed,
  count(*) filter (where event_name = 'tailored_session_dropoff')::int as sessions_dropped,
  case
    when count(*) filter (where event_name = 'tailored_session_start') = 0 then 0::numeric
    else round(
      (count(*) filter (where event_name = 'tailored_session_complete'))::numeric
      / nullif(count(*) filter (where event_name = 'tailored_session_start'), 0),
      4
    )
  end as completion_rate
from public.analytics_events
where event_name in ('tailored_session_start', 'tailored_session_complete', 'tailored_session_dropoff');
alter view public.analytics_tailored_summary set (security_invoker = true);

create or replace view public.analytics_funnel_summary as
select
  count(*) filter (where event_name = 'landing_page_view')::int as page_views,
  count(*) filter (where event_name = 'landing_cta_click')::int as cta_clicks,
  count(*) filter (where event_name = 'signup_start')::int as signup_starts,
  count(*) filter (where event_name = 'signup_complete')::int as signup_completes
from public.analytics_events
where event_name in ('landing_page_view', 'landing_cta_click', 'signup_start', 'signup_complete');
alter view public.analytics_funnel_summary set (security_invoker = true);

grant select on public.analytics_audio_summary to authenticated;
grant select on public.analytics_tailored_summary to authenticated;
grant select on public.analytics_funnel_summary to authenticated;
